# Cambios:
# cellVariable -> numVariable
# connections

# Hace falta incluir los objetos del juego específico ?
# - Leer objetos left-most objects en descripción VGDL
# - Añadir objetos devueltos por GVGAI
gameElementsCorrespondence:
  avatar:
  - (at ?n1 ?n2 ?avatar)
variablesTypes:
  ?avatar: avatar
  ?n0: num
  ?n1: num
numVariable: ?n
avatarVariable: ?avatar

# Esto habrá que modificarlo según el juego

orientationCorrespondence:
  UP: (oriented-up ?object)
  DOWN: (oriented-down ?object)
  LEFT: (oriented-left ?object)
  RIGHT: (oriented-right ?object)
connections:
  NEXT: (next ?n1 ?n2)
  PREVIOUS: (previous ?n1 ?n2)

