# Cambios:
# cellVariable -> numVariable
# connections
gameElementsCorrespondence:
  wall:
  - (row ?wall)
  - (column ?wall)
  sword:
  - (row ?sword)
  - (column ?sword)
  dirt:
  - (row ?dirt)
  - (column ?dirt)
  exitdoor:
  - (row ?exitdoor)
  - (column ?exitdoor)
  diamond:
  - (row ?diamond)
  - (column ?diamond)
  boulder:
  - (row ?boulder)
  - (column ?boulder)
  avatar:
  - (row ?avatar)
  - (column ?avatar)
  crab:
  - (row ?crab)
  - (column ?crab)
  butterfly:
  - (row ?butterfly)
  - (column ?butterfly)
variablesTypes:
  ?wall: wall
  ?sword: sword
  ?dirt: dirt
  ?exitdoor: exitdoor
  ?diamond: diamond
  ?boulder: boulder
  ?avatar: avatar
  ?crab: crab
  ?butterfly: butterfly
avatarVariable: ?avatar

# Esto habrá que modificarlo según el juego

orientationCorrespondence:
  UP: (oriented-up ?avatar)
  DOWN: (oriented-down ?avatar)
  LEFT: (oriented-left ?avatar)
  RIGHT: (oriented-right ?avatar)


