gameElementsCorrespondence:
  wall:
  - (at ?c ?wall)
  sword:
  - (at ?c ?sword)
  dirt:
  - (at ?c ?dirt)
  exitdoor:
  - (at ?c ?exitdoor)
  diamond:
  - (at ?c ?diamond)
  boulder:
  - (at ?c ?boulder)
  avatar:
  - (at ?c ?avatar)  
  crab:
  - (at ?c ?crab)
  butterfly:
  - (at ?c ?butterfly)
variablesTypes:
  ?wall: wall
  ?sword: sword
  ?dirt: dirt
  ?exitdoor: exitdoor
  ?diamond: diamond
  ?boulder: boulder
  ?avatar: avatar
  ?crab: crab
  ?butterfly: butterfly
  ?c: cell
cellVariable: ?c
avatarVariable: ?avatar

# Esto habrá que modificarlo según el juego

orientationCorrespondence:
  UP: (oriented-up ?avatar)
  DOWN: (oriented-down ?avatar)
  LEFT: (oriented-left ?avatar)
  RIGHT: (oriented-right ?avatar)
connections:
  UP: (connected-up ?c ?u)
  DOWN: (connected-down ?c ?d)
  LEFT: (connected-left ?c ?l)
  RIGHT: (connected-right ?c ?r)

